"""Freeze visually grounded native sample before inference."""
from pathlib import Path
import json,hashlib,sys
r=Path(__file__).resolve().parent;s=Path(sys.argv[1]);m=json.loads((s/'manifest.json').read_text());sources=[c for c in m['candidates'] if c['id'] in ['06','07','08']]
for c in sources:assert hashlib.sha256((s/c['file']).read_bytes()).hexdigest()==c['sha256']
pages=[
 dict(source_id='06',page=4,printed=4,anchors=['Three-Layer Knowledge Architecture','Raw Layer','Wiki Layer'],order=['Figure 2','3. Methodology','3.1. Three-Layer Knowledge Architecture']),
 dict(source_id='06',page=5,printed=5,anchors=['Skill Provisioning for the Inference Agent','Wiki Maintainer: Pattern Consolidation'],order=['3.2. Evolutionary Agents and Wiki Orchestration','3.2.1. Skill Provisioning','3.2.2. Wiki Maintainer']),
 dict(source_id='06',page=8,printed=8,anchors=['38.5','47.4','68.1'],order=['Table 1','The benefits of skill evolution increase with model capability']),
 dict(source_id='07',page=3,printed=3,anchors=['YOLOv1 (2015)','YOLOv26 (2025)'],order=['Table 1','Cross-Stage Partial Networks','Ultralytics, the primary maintainer']),
 dict(source_id='07',page=5,printed=5,anchors=['Architectural Enhancements in YOLO26','Figure 3'],order=['Architectural Enhancements in YOLO26','Figure 3']),
 dict(source_id='08',page=86,printed=67,anchors=['Figure 3.1','transition model','goal test'],order=['Figure 3.1','possible actions','transition model','goal test']),
 dict(source_id='08',page=87,printed=68,anchors=['Figure 3.2','3.1.2','Formulating problems'],order=['Figure 3.2','path cost','3.1.2']),
 dict(source_id='08',page=104,printed=85,anchors=['278','Depth-first search','LIFO queue'],order=['Uniform-cost search does not care','Depth-first search','LIFO queue'])]
figures=[dict(source_id=i,page=p,caption=c,bbox=b,labels=l) for i,p,c,b,l in [('06',4,'Figure 2',[70,80,535,305],['Skill Layer','Raw Layer','Skill Proposer','Gating & Rollback']),('07',5,'Figure 3',[100,310,520,690],['Backbone','Neck','Head','Detect','Upsample']),('08',86,'Figure 3.1',[100,70,508,268],['seq','percept']),('08',87,'Figure 3.2',[102,65,508,312],['Arad','Bucharest','Sibiu','140','99'])]]
plan=dict(scope='Revised v1: born-digital papers and selected book chapter. Scanned/historical/faulty-layer repair/automatic OCR selection deferred, not passed. PPT-export absent; EN samples do not establish multilingual or multicolumn-prose coverage.',sources=[{k:c[k] for k in ['id','file','title','sha256','bytes','source_revision_reference']} for c in sources],book_chapter='Chapter 3 — Solving Problems by Searching; physical pages=printed+19 for selected pages',pages=pages,figures=figures,tables=[dict(source_id='06',page=8,expected_rows=26,expected_cols=8,association='Five model blocks, each spanning five method rows; header=Model,Method,LiveMath,SealQA,SpreadSheet,OfficeQA,ALFWorld,Avg.',cells=[{'row':5,'col':7,'value':'38.5'},{'row':10,'col':7,'value':'47.4'},{'row':25,'col':7,'value':'68.1'}]),dict(source_id='07',page=3,expected_rows=15,expected_cols=4,association='14 model rows plus header; model/year aligned with innovation, tasks and framework',cells=[{'row':1,'col':0,'value':'YOLOv1 (2015)'},{'row':14,'col':0,'value':'YOLOv26 (2025)'},{'row':1,'col':3,'value':'Darknet'}])],formula_regions=[dict(source_id='06',page=5,bbox=[250,575,538,608],description='Equation (1): tau_i sampled from pi(x_i; S_k-1). Preserve source pixels and page-region evidence; do not claim formula interpretation.'),dict(source_id='08',page=86,bbox=[148,433,385,461],description='Displayed RESULT(In(Arad), Go(Zerind)) = In(Zerind); preserve source evidence, no enrichment.')],paragraphs=[dict(source_id='08',page=87,text='The preceding elements of a problem can be gathered into a single data structure that is given as input to a problem-solving algorithm. A solution to a problem is an action sequence that leads from the initial state to a goal state. Solution quality is measured by the path cost function, and an optimal solution has the lowest path cost among all solutions.'),dict(source_id='08',page=104,text='Uniform-cost search does not care about the number of steps a path has, but only about their total cost. Therefore, it will get stuck in an infinite loop if there is a path with an infinite sequence of zero-cost actions—for example, a sequence of NoOp actions. Completeness is guaranteed provided the cost of every step exceeds some small positive constant ε.')],criteria='Predeclared diagnostics, not user-approved universal thresholds: whitespace-only exact anchor and complete paragraph match, first-occurrence reading order, exact table geometry/cell mapping, picture caption references and source bbox coverage. Record mismatch and invalid probes explicitly; do not silently relax criteria. Crops are manual controls, not production selection. Full-document completeness and semantic formula correctness are not claimed.',coordinates='Top-left PDF points from visual renders; preserve region PNGs locally, hash and record actual detected boxes. Native text existence is not proof reliable character mapping.')
(r/'plan.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2));print(hashlib.sha256((r/'plan.json').read_bytes()).hexdigest())
