"""THROWAWAY S2. prepare freezes expectations; measure runs real direct recognition."""
import argparse, hashlib, json, os, platform, sys, time
from pathlib import Path
ROOT=Path(__file__).resolve().parent
OUT=ROOT/'artifacts'
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(p,x): p.write_text(json.dumps(x,ensure_ascii=False,indent=2))
def prepare(preserve_aspect=False):
    from PIL import Image,ImageDraw,ImageFont,ImageFilter
    from reportlab.pdfgen.canvas import Canvas
    from reportlab.lib.utils import ImageReader
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.cidfonts import UnicodeCIDFont
    import random
    OUT.mkdir(exist_ok=True)
    fontpath=Path('/System/Library/Fonts/STHeiti Medium.ttc')
    font=ImageFont.truetype(str(fontpath),42)
    pdfmetrics.registerFont(UnicodeCIDFont('MSung-Light'))
    from reportlab.pdfbase.ttfonts import TTFont
    pdfmetrics.registerFont(TTFont('S2TC',str(fontpath)))
    cases=[
      ('native_mixed',['Knowledge processing','知識處理流程','PDF OCR 版本 2026'],'native'),
      ('scan_en',['Knowledge processing','Review source evidence','Version 2026'],'scan'),
      ('scan_tc',['知識處理流程','檢查來源證據','版本更新完成'],'scan'),
      ('scan_mixed',['Knowledge processing','檢查來源證據','PDF OCR 版本 2026'],'scan'),
      ('small_bitmap',['圖像辨識結果','OCR 版本 2026'],'small'),
      ('faulty_layer',['檢查來源證據','正確版本 2026'],'faulty'),
      ('degraded_tc',['知識處理流程','檢查來源證據','版本更新完成'],'degraded')]
    c=Canvas(str(OUT/'matrix.pdf'),pagesize=(612,792),invariant=1)
    matrix=[]
    for n,(name,lines,kind) in enumerate(cases,1):
      im=Image.new('RGB',(1100,420),'white'); d=ImageDraw.Draw(im)
      for i,line in enumerate(lines): d.text((30,25+i*110),line,font=font,fill='black')
      if kind=='degraded':
        im=im.rotate(1.5,resample=Image.Resampling.BICUBIC,expand=False,fillcolor='white').filter(ImageFilter.GaussianBlur(.65))
        rng=random.Random(35); px=im.load()
        for _ in range(3500):
          x,y=rng.randrange(im.width),rng.randrange(im.height); v=rng.randrange(130,255); px[x,y]=(v,v,v)
      crop=OUT/(name+'.png'); im.save(crop)
      if kind=='native':
        c.setFont('S2TC' if preserve_aspect else 'MSung-Light',20)
        for i,line in enumerate(lines): c.drawString(50,700-i*55,line)
        rect=[50,540,560,735]
      elif kind=='small':
        c.setFont('Helvetica',16);c.drawString(50,730,'Native surrounding paragraph')
        c.drawImage(ImageReader(im),50,570,width=275,height=105);rect=[50,570,325,675]
      else:
        height=552*420/1100 if preserve_aspect else 732
        bottom=550 if preserve_aspect else 30
        c.drawImage(ImageReader(im),30,bottom,width=552,height=height);rect=[30,bottom,582,bottom+height]
        if kind=='faulty':
          t=c.beginText(50,680);t.setFont('Helvetica',20);t.setTextRenderMode(3)
          for line in ['WRONG SOURCE TEXT','INCORRECT VERSION 0000']:t.textLine(line)
          c.drawText(t)
      matrix.append(dict(page=n,id=name,kind=kind,expected_lines=lines,required_tokens=lines,crop=crop.name,crop_sha256=sha(crop),bbox_bottomleft_points=rect))
      c.showPage()
    c.save()
    manifest=dict(question='Can pinned baseline preserve exact required synthetic content across EN/Traditional Chinese/mixed paths?',source='Original synthetic text authored for issue #35; no external document text. Fixtures generated by this script. Font is system-provided STHeiti; font not redistributed.',minimum='PREDECLARED PROVISIONAL: every required line occurs after whitespace normalization, in order; all nonempty Docling text items carry valid page provenance. Human review of these minima and representativeness is outstanding; this is not an adoption approval.',scan_geometry='aspect-preserving image region' if preserve_aspect else 'anisotropically stretched full-page image; stress case, not ordinary scan',baseline='85925faa5b6167ee6e750fd02a0f3930d7ed8089',font_sha256=sha(fontpath),pdf_sha256=sha(OUT/'matrix.pdf'),cases=matrix)
    dump(OUT/'manifest.json',manifest)
    print('Prepared manifest SHA256',sha(OUT/'manifest.json'))
def measure(cache):
    os.environ['HF_HOME']=str(Path(cache).resolve());os.environ['HF_HUB_OFFLINE']='1';os.environ['OMP_NUM_THREADS']='4'
    import importlib.metadata as md
    from docling.datamodel.base_models import InputFormat
    from docling.datamodel.pipeline_options import ThreadedPdfPipelineOptions,RapidOcrOptions
    from docling.datamodel.accelerator_options import AcceleratorOptions,AcceleratorDevice
    from docling.document_converter import DocumentConverter,PdfFormatOption
    from rapidocr import RapidOCR
    manifest=json.loads((OUT/'manifest.json').read_text());assert sha(OUT/'matrix.pdf')==manifest['pdf_sha256']
    def check(text,lines):
      norm=lambda s:''.join(s.split())
      text=norm(text); pos=-1;found=[]
      for line in lines:
        q=text.find(norm(line),pos+1); found.append(q>=0)
        if q>=0:pos=q
      return dict(required_lines_found=found,all_required_in_order=all(found))
    env=dict(platform=platform.platform(),python=sys.version,packages={d.metadata['Name']:d.version for d in md.distributions()},manifest_sha256=sha(OUT/'manifest.json'),models={str(p.relative_to(Path(cache))):sha(p) for p in Path(cache).rglob('*') if p.is_file()},profiles={})
    rapid_path=Path(__import__('rapidocr').__file__).parent
    env['rapidocr_models']={str(p.relative_to(rapid_path)):sha(p) for p in rapid_path.rglob('*.onnx')}
    dump(OUT/'environment.json',env)
    for name,ocr,full in [('native',False,False),('mixed',True,False),('scanned',True,True)]:
      opts=ThreadedPdfPipelineOptions(do_ocr=ocr,ocr_options=RapidOcrOptions(backend='onnxruntime',force_full_page_ocr=full),do_table_structure=True,generate_page_images=True,generate_picture_images=True,images_scale=1,accelerator_options=AcceleratorOptions(device=AcceleratorDevice.CPU,num_threads=4))
      env['profiles'][name]=opts.model_dump(mode='json');dump(OUT/'environment.json',env)
      start=time.monotonic();result=DocumentConverter(format_options={InputFormat.PDF:PdfFormatOption(pipeline_options=opts)}).convert(OUT/'matrix.pdf')
      result.document.save_as_json(OUT/(name+'.json')); result.document.save_as_markdown(OUT/(name+'.md'))
      pages={i:[] for i in range(1,8)};invalid=[]
      for item,_ in result.document.iterate_items():
        if not getattr(item,'text',''):continue
        if not item.prov:invalid.append(item.self_ref)
        for prov in item.prov:
          if prov.page_no in pages:pages[prov.page_no].append(item.text)
          else:invalid.append(item.self_ref)
      rows=[]
      for case in manifest['cases']:
        txt='\n'.join(pages[case['page']]);rows.append(dict(id=case['id'],text=txt,**check(txt,case['required_tokens'])))
      dump(OUT/(name+'-scores.json'),dict(status=str(result.status),seconds=time.monotonic()-start,invalid_provenance=invalid,cases=rows))
      print(name,[(r['id'],r['all_required_in_order']) for r in rows],flush=True)
    engine=RapidOCR();rows=[]
    for case in manifest['cases']:
      output=engine(str(OUT/case['crop']));txt='\n'.join(output.txts or [])
      rows.append(dict(id=case['id'],text=txt,scores=[] if output.scores is None else [float(x) for x in output.scores],**check(txt,case['required_tokens'])))
    dump(OUT/'crop-scores.json',rows);print('crops',[(r['id'],r['all_required_in_order']) for r in rows],flush=True)
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('command',choices=['prepare','measure']);p.add_argument('--cache');p.add_argument('--preserve-aspect',action='store_true');p.add_argument('--output',default='artifacts');a=p.parse_args();OUT=ROOT/a.output
    prepare(a.preserve_aspect) if a.command=='prepare' else measure(a.cache)
